import { useEffect, useState } from 'react';
import PropTypes from 'prop-types';
import { useTheme } from './context/ThemeContext';
import { useStudents } from './context/StudentContext';

function StatBadge({label,value}){return <div className="stat"><span>{label}</span><strong>{value}</strong></div>}
StatBadge.propTypes={label:PropTypes.string.isRequired,value:PropTypes.oneOfType([PropTypes.string,PropTypes.number]).isRequired};
function CourseTag({courseName,index}){return <span className={`course ${['blue','violet','green','amber','pink'][index%5]}`}>{courseName}</span>}
CourseTag.propTypes={courseName:PropTypes.string.isRequired,index:PropTypes.number.isRequired};
function DashboardHeader(){const {displayed,favorites}=useStudents();const {theme,toggleTheme}=useTheme();return <header className="header"><nav><a className="brand" href="#top">Campus<span>Hub</span></a><div><a href="#students">Students</a><a href="#add">Add Student</a><button className="themeToggle" onClick={toggleTheme}>{theme==='light'?'◐ Dark':'☀ Light'}</button></div></nav><div className="hero"><div><p className="eyebrow">COMPLETE PORTAL</p><h1>Student Dashboard</h1><p>Manage your student community in one place.</p></div><div className="headerStats"><StatBadge label="Showing" value={displayed.length}/><StatBadge label="Favorites" value={favorites.length}/></div></div></header>}
function SearchBar(){const {query,setQuery}=useStudents();return <label className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by name or major..." aria-label="Search students"/></label>}
function SortControls(){const {sort,setSort}=useStudents();return <div className="sort">{[['default','Default'],['name','Name A-Z'],['gpa','Top GPA']].map(([key,label])=><button className={sort===key?'active':''} key={key} onClick={()=>setSort(key)}>{label}</button>)}</div>}
function StudentCard({student}){const {favorites,toggleFavorite,removeStudent}=useStudents();const favorite=favorites.includes(student.id);return <article className="card"><button className={`favorite ${favorite?'selected':''}`} onClick={()=>toggleFavorite(student.id)} aria-label={`Favorite ${student.name}`}>{favorite?'★':'☆'}</button><div className="cardTop"><div className="avatar">{student.avatar}</div><div><h2>{student.name}</h2><p>{student.major}</p><small>ID {student.id}</small></div></div><div className="stats"><StatBadge label="GPA" value={Number(student.gpa).toFixed(2)}/><StatBadge label="Credits" value={student.credits||0}/></div><div className="cardFooter"><div className="courses">{student.courses.map((course,index)=><CourseTag key={course[0]||course} courseName={course[0]||course} index={index}/>)}</div><button className="remove" onClick={()=>removeStudent(student.id)}>Remove</button></div></article>}
StudentCard.propTypes={student:PropTypes.object.isRequired};
function AddStudentForm(){const {students,addStudent}=useStudents();const empty={name:'',id:'',major:'',gpa:'',courses:''};const [form,setForm]=useState(empty),[errors,setErrors]=useState({}),[success,setSuccess]=useState(false);useEffect(()=>{if(!success)return;const timer=setTimeout(()=>setSuccess(false),3000);return()=>clearTimeout(timer)},[success]);const validate=()=>{const next={};if(!form.name.trim())next.name='Full name is required.';if(!/^\d+$/.test(form.id))next.id='Student ID must be numeric.';else if(students.some(s=>s.id===form.id))next.id='This Student ID already exists.';if(!form.major.trim())next.major='Major is required.';const gpa=Number(form.gpa);if(form.gpa===''||gpa<0||gpa>4)next.gpa='GPA must be between 0 and 4.0.';return next};const submit=e=>{e.preventDefault();const next=validate();setErrors(next);if(Object.keys(next).length)return;addStudent({name:form.name.trim(),id:form.id,major:form.major.trim(),gpa:Number(form.gpa),courses:form.courses.split(',').map(c=>c.trim()).filter(Boolean),avatar:form.name.split(/\s+/).map(p=>p[0]).slice(0,2).join('').toUpperCase(),credits:0});setForm(empty);setSuccess(true)};const field=(name,value)=>setForm(current=>({...current,[name]:value}));return <section className="formPanel" id="add"><div><p className="eyebrow">REGISTRATION</p><h2>Add a new student</h2><p>Complete the profile and it will appear instantly in the dashboard.</p></div><form onSubmit={submit} noValidate>{success&&<div className="success">✓ Student added successfully.</div>}<div className="formGrid"><label>Full Name<input value={form.name} onChange={e=>field('name',e.target.value)} placeholder="e.g. Farah Khan"/>{errors.name&&<small>{errors.name}</small>}</label><label>Student ID<input value={form.id} onChange={e=>field('id',e.target.value)} placeholder="Numeric ID"/>{errors.id&&<small>{errors.id}</small>}</label><label>Major<input value={form.major} onChange={e=>field('major',e.target.value)} placeholder="e.g. Computer Science"/>{errors.major&&<small>{errors.major}</small>}</label><label>GPA<input type="number" step="0.01" value={form.gpa} onChange={e=>field('gpa',e.target.value)} placeholder="0.00 - 4.00"/>{errors.gpa&&<small>{errors.gpa}</small>}</label><label className="full">Courses<input value={form.courses} onChange={e=>field('courses',e.target.value)} placeholder="React, Databases, Algorithms"/></label></div><button className="submit" type="submit">Add student →</button></form></section>}
export default function App(){const {displayed}=useStudents();return <><DashboardHeader/><main id="students"><div className="toolbar"><SearchBar/><SortControls/></div>{displayed.length?<section className="grid">{displayed.map(student=><StudentCard key={student.id} student={student}/>)}</section>:<div className="empty"><h2>No students found</h2><p>Try another search or add a new student below.</p></div>}<AddStudentForm/></main><footer>React Lab 03 · Context, Forms & Persistence</footer></>}
