import { useEffect, useMemo, useState } from 'react';
import PropTypes from 'prop-types';
import './lab2.css';

const seedStudents=[
 {id:'2024001',name:'Aisha Rahman',avatar:'AR',gpa:3.92,major:'Computer Science',credits:96,courses:[['React','blue'],['Algorithms','violet']]},
 {id:'2024002',name:'Nafis Ahmed',avatar:'NA',gpa:3.74,major:'Software Engineering',credits:84,courses:[['Node.js','green'],['Databases','amber']]},
 {id:'2024003',name:'Sadia Karim',avatar:'SK',gpa:3.86,major:'Information Systems',credits:78,courses:[['UI/UX','pink'],['Networks','blue']]},
 {id:'2024004',name:'Tanvir Hasan',avatar:'TH',gpa:3.65,major:'Data Science',credits:90,courses:[['Python','green'],['Machine Learning','violet']]},
];
function StatBadge({label,value}){return <div className="stat"><span>{label}</span><strong>{value}</strong></div>}
StatBadge.propTypes={label:PropTypes.string.isRequired,value:PropTypes.oneOfType([PropTypes.string,PropTypes.number]).isRequired};
function CourseTag({courseName,color}){return <span className={`course ${color}`}>{courseName}</span>}
CourseTag.propTypes={courseName:PropTypes.string.isRequired,color:PropTypes.string.isRequired};
function DashboardHeader({studentCount,favoriteCount}){return <header className="header"><nav><a className="brand" href="#top">Campus<span>Hub</span></a><div><a href="#students">Students</a><a href="#overview">Overview</a></div></nav><div className="hero"><div><p className="eyebrow">INTERACTIVE PORTAL</p><h1>Student Dashboard</h1><p>Search, sort and save the students you follow.</p></div><div className="headerStats"><StatBadge label="Showing" value={studentCount}/><StatBadge label="Favorites" value={favoriteCount}/></div></div></header>}
DashboardHeader.propTypes={studentCount:PropTypes.number.isRequired,favoriteCount:PropTypes.number.isRequired};
function SearchBar({query,onChange}){return <label className="search"><span>⌕</span><input value={query} onChange={e=>onChange(e.target.value)} placeholder="Search by name or major..." aria-label="Search students"/></label>}
SearchBar.propTypes={query:PropTypes.string.isRequired,onChange:PropTypes.func.isRequired};
function SortControls({value,onChange}){return <div className="sort">{[['default','Default'],['name','Name A-Z'],['gpa','Top GPA']].map(([key,label])=><button className={value===key?'active':''} key={key} onClick={()=>onChange(key)}>{label}</button>)}</div>}
SortControls.propTypes={value:PropTypes.string.isRequired,onChange:PropTypes.func.isRequired};
function StudentCard({student,onFavoriteChange}){const [favorite,setFavorite]=useState(false);const toggle=()=>{const next=!favorite;setFavorite(next);onFavoriteChange(student.id,next)};return <article className="card"><button className={`favorite ${favorite?'selected':''}`} onClick={toggle} aria-label={`Favorite ${student.name}`}>{favorite?'★':'☆'}</button><div className="cardTop"><div className="avatar">{student.avatar}</div><div><h2>{student.name}</h2><p>{student.major}</p><small>ID {student.id}</small></div></div><div className="stats"><StatBadge label="GPA" value={student.gpa.toFixed(2)}/><StatBadge label="Credits" value={student.credits}/></div><div className="courses">{student.courses.map(([course,color])=><CourseTag key={course} courseName={course} color={color}/>)}</div></article>}
StudentCard.propTypes={student:PropTypes.object.isRequired,onFavoriteChange:PropTypes.func.isRequired};
export default function App(){const [students,setStudents]=useState([]),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[sort,setSort]=useState('default'),[favorites,setFavorites]=useState([]);useEffect(()=>{const timer=setTimeout(()=>{setStudents(seedStudents);setLoading(false)},1500);return()=>clearTimeout(timer)},[]);const displayed=useMemo(()=>{const q=query.toLowerCase().trim();const result=students.filter(s=>s.name.toLowerCase().includes(q)||s.major.toLowerCase().includes(q));if(sort==='name')return [...result].sort((a,b)=>a.name.localeCompare(b.name));if(sort==='gpa')return [...result].sort((a,b)=>b.gpa-a.gpa);return result},[students,query,sort]);useEffect(()=>{document.title=`Dashboard - ${displayed.length} Student${displayed.length===1?'':'s'}`},[displayed.length]);const updateFavorite=(id,selected)=>setFavorites(current=>selected?[...new Set([...current,id])]:current.filter(item=>item!==id));return <><DashboardHeader studentCount={displayed.length} favoriteCount={favorites.length}/><main id="students"><div className="toolbar"><SearchBar query={query} onChange={setQuery}/><SortControls value={sort} onChange={setSort}/></div>{loading?<div className="loading"><div className="spinner"/><h2>Loading students...</h2></div>:displayed.length?<section className="grid">{displayed.map(student=><StudentCard key={student.id} student={student} onFavoriteChange={updateFavorite}/>)}</section>:<div className="loading"><h2>No students found</h2><p>Try a different search term.</p></div>}</main><footer>React Lab 02 · State, Effects & Interactivity</footer></>}
